services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: acme-widget-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - acme-widget-network

  nginx:
    image: nginx:alpine
    container_name: acme-widget-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - acme-widget-network

networks:
  acme-widget-network:
    driver: bridge 